[package]
name = "multi-threading"
version = "0.0.1"
authors = ["John Sharratt <john.sharratt@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "An example TCP client."
repository = "https://github.com/wasmerio/ate"
readme = "README.md"
keywords = [
    "wasm",
    "tcp",
]
categories = []
edition = "2021"

[dependencies]
once_cell = "1.12"
