[package]
name = "tcp-listener"
version = "0.0.1"
authors = ["John Sharratt <john.sharratt@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "An example TCP listener."
repository = "https://github.com/wasmerio/ate"
readme = "README.md"
keywords = [
    "wasm",
    "tcp",
]
categories = ["network-programming"]
edition = "2021"
